const colors = {
  primary: {
    default: "#001D29",
    hover: "#1a343e",
    pressed: "#40565F",
    disabled: "#E5E9EA",
    text: "white",
    textDisabled: "#66777E",
  },
  secondary: {
    default: "transparent",
    hover: "transparent",
    pressed: "transparent",
    disabled: "transparent",
    border: "#001D29",
    borderHover: "#1a343e",
    borderPressed: "#40565F",
    borderDisabled: "#E5E9EA",
    text: "#001D29",
    textHover: "#1a343e",
    textPressed: "#40565F",
    textDisabled: "#66777E",
  },
  additional: {
    default: "transparent",
    hover: "transparent",
    pressed: "transparent",
    disabled: "transparent",
    border: "#E71D36",
    borderHover: "#EC4A5E",
    borderPressed: "#E02A36B2",
    borderDisabled: "#E5E9EA",
    text: "#E71D36",
    textHover: "#EC4A5E",
    textPressed: "#E02A36B2",
    textDisabled: "#66777E",
  },
  primary1: {
    default: "#001D29",
    hover: "#1a343e",
    pressed: "#40565F",
    disabled: "#E5E9EA",
    text: "white",
    textDisabled: "#66777E",
    width: "60px",
    height: "32px",
    padding: "4px 12px",
    fontSize: "12px",
  },
  secondary1: {
    default: "transparent",
    hover: "transparent",
    pressed: "transparent",
    disabled: "transparent",
    border: "#007EB0",
    borderHover: "#409EC4",
    borderPressed: "#66B2D0",
    borderDisabled: "#E5E9EA",
    text: "#007EB0",
    textHover: "#409EC4",
    textPressed: "#66B2D0",
    textDisabled: "#66777E",
    width: "60px",
    height: "32px",
    padding: "4px 12px",
    fontSize: "12px",
  },
  outline1: {
    default: "transparent",
    hover: "#F7FBFC",
    pressed: "#E5E9EA",
    disabled: "transparent",
    text: "#001D29",
    textDisabled: "#66777E",
    width: "60px",
    height: "32px",
    padding: "4px 12px",
    fontSize: "12px",
  },
  outline2: {
    default: "transparent",
    hover: "transparent",
    pressed: "transparent",
    disabled: "transparent",
    border: "#001D29",
    borderHover: "#1a343e",
    borderPressed: "#40565F",
    borderDisabled: "#E5E9EA",
    text: "#001D29",
    textHover: "#1a343e",
    textPressed: "#40565F",
    textDisabled: "#66777E",
    width: "60px",
    height: "32px",
    padding: "4px 12px",
    fontSize: "12px",
  },
  outline3: {
    default: "transparent",
    hover: "#F7FBFC",
    pressed: "#E5E9EA",
    disabled: "transparent",
    text: "#001D29",
    textDisabled: "#66777E",
    width: "40px",
    height: "14px",
    fontSize: "12px",
    padding: "0",
    borderRadius: "4px",
  },
  outline4: {
    default: "#007EB0",
    hover: "#1a8bb8",
    pressed: "#409ec4",
    disabled: "#E5E9EA",
    text: "white",
    textDisabled: "#66777E",
    width: "60px",
    height: "32px",
    padding: "4px 12px",
    fontSize: "12px",
  },
};

export default colors;
